### ISSUE TITLE
Question about using Resource module for Network Device to create a new device

### ISSUE THREAD

**Issue by kiwi-stefan** [CiscoISE/ansible-ise#10]
Hi, I am struggling to find out how to set the variable getIpaddressExclude inside:
NetworkDeviceIPList:
    - getIpaddressExclude: string
      ipaddress: string
      mask: 0
What should I put in here? Do you have an example?

Rgds
Stefan

**Comment by aussietexan** [comment]
The 'getIpAddressExclude' key is not required. It would only be used if you wanted to create a network device object using a range (e.g. 1.1.1.1-10) and exclude something within that range (e.g. 1.1.1.5).
When creating a new network device, there are mandatory values that must be set like IP address/range, name, profile, etc, and other optional values. The following playbook would work for creating a basic network device with RADIUS enabled and all other values set to defaults.
`- hosts: ise_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
  - name: Create new NAD
    cisco.ise.network_device:
      ise_hostname: "{{ise_hostname}}"
      ise_username: "{{ise_username}}"
      ise_password: "{{ise_password}}"
      ise_verify: "{{ise_verify}}"
      state: present
      NetworkDeviceIPList:
      - ipaddress: "1.1.1.1"
        mask: 32
      name: "testnad"
      profile: "Cisco"
      authenticationSettings:
        networkProtocol: "RADIUS"
        radiusSharedSecret: "cisco123"`
