### ISSUE TITLE
Module network_device_group does not work

### ISSUE THREAD

**Issue by cmnarducci** [CiscoISE/ansible-ise#113]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
The module `cisco.ise.network_device_group` does not work with latest patches of ISE 3.1 (patch8) and ISE 3.2 (patch4).
The module uses the attribute `ndgtype` while the ISE API uses the attribute `othername`.

**Expected behavior**
Revert back to `othername` in the module `cisco.ise.network_device_group`.

**Environment (please complete the following information):**
* ISE version and patch:  3.1 patch 8, 3.2 patch 4
* Ansible version: 9.1.0
* ISE collection version: 2.6.2
* OS version: RockyLinux 9.2

**Comment by susanhooks** [comment]
Looks to be resolved in ansible-ise 2.9.1, SDK 2.2.1, ISE version 3.3.
