### ISSUE TITLE
cisco.ise.network_device missing state option

### ISSUE THREAD

**Issue by markatdxb** [CiscoISE/ansible-ise#115]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
documentation is missing State option
module works as expected based on samples description

**Expected behavior**
update missing documentation

**Comment by fmunozmiranda** [comment]
State is specified in samples.
