### ISSUE TITLE
ISE expects `filtertype` but module is sending `filterType` which doesn't return any result

### ISSUE THREAD

**Issue by phuchet1001** [CiscoISE/ansible-ise#116]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?
* [x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
Listing endpoints while using `filterType: or` fails. The module is sending `filterType=or` in the URL, when it should be `filtertype=or`. ISE does not return any result when module is used.

**Expected behavior**

Module should send `filtertype=or` in the URL and there should be results returned by ISE.

**Screenshots**

Logs of the module usage from `ansible-console`

```
user@localhost (1)[f:5]$ cisco.ise.endpoint_info ise_username="admin" ise_password="Winter2024!" ise_hostname="wireless-pan.isecube.cisco.com" ise_debug=true ise_verify=false user=or filter=staticGroupAssignment.EQ.true,staticProfileAssignment.EQ.true
Attempt 1

Request
        URL: https://wireless-pan.isecube.cisco.com/ers/config/endpoint
        Method: GET
        Headers: 
                User-Agent: python-requests/2.31.0
                Accept-Encoding: gzip, deflate
                Accept: application/json
                Connection: keep-alive
                authorization: Basic YWRtaW46V2ludGVyMjAyNCE=
                Content-type: application/json;charset=utf-8
        Params:
              {
                  "filter": [
                      "staticGroupAssignment.EQ.true",
                      "staticProfileAssignment.EQ.true"
                  ],
                  "user": "or"
              }

Response
        Status: 200 - 
        Headers: 
                Content-Type: application/json;charset=utf-8
                Transfer-Encoding: chunked
                Connection: keep-alive
                Cache-Control: no-cache, no-store, must-revalidate
                Set-Cookie: JSESSIONIDSSO=462D34E09640B18E545EC4CBD54F97AB; Path=/; Secure; HttpOnly, APPSESSIONID=1D2FDD978801F9980F46572C5FCA6EBE; Path=/ers; Secure; HttpOnly
                Pragma: no-cache
                Expires: Thu, 01 Jan 1970 00:00:00 GMT
                X-Frame-Options: SAMEORIGIN
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Content-Type-Options: nosniff
                X-Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-WebKit-CSP: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;
                X-XSS-Protection: 1; mode=block
                Date: Wed, 17 Jan 2024 22:11:18 GMT
                Server: 
        Body:
             {
                 "SearchResult": {
                     "total": 0,
                     "resources": []
                 }
             }
localhost | SUCCESS => {
    "changed": false,
    "ise_response": [],
    "result": ""
}
user@localhost (1)[f:5]$ 
```

Request sent by the module, for which ISE returns 0 results.

![Screenshot 2024-01-17 at 4 16 27 PM](https://github.com/CiscoISE/ansible-ise/assets/103665600/be069ea4-33e5-4478-a23f-4c4dfa874847)

Request sent from curl, with `filtertype=or`, for which ISE returns expected results.

![Screenshot 2024-01-17 at 4 18 57 PM](https://github.com/CiscoISE/ansible-ise/assets/103665600/dab5881f-e133-45d3-895c-0d956d9948b3)

**Environment (please complete the following information):**
* ISE version and patch: ISE 3.2 patch 3
* Ansible version: 2.15.5
* ISE collection version: 2.5.16
* OS version: Mac OS

**Comment by bvargasre** [comment]
Hi @phuchet1001 the new version of ansible-ise 2.9.3 is now available
This version fixed the problem, try the new version and let us know
I'm going to close this issue, in case the problem persists feel free to reopen it or create a new one
Regards
