### ISSUE TITLE
cisco.ise.active_directory module requires too many attributes to create join point

### ISSUE THREAD

**Issue by grg1bbs** [CiscoISE/ansible-ise#132]
**Prerequisites**
* [ x] Have you tested the operation in the API directly?
* [ x] Do you have the latest ISE Collection version?
* [ x] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
When using the module to create a simple AD Join Point, the module throws an exception error due to non-required attributes.

Although the API documentation shows multiple required attributes, the list attributes are only required if parent attribute is required.
https://developer.cisco.com/docs/identity-services-engine/latest/activedirectory/

**Example code**

  - name: Create AD Join Point
    cisco.ise.active_directory:
      <<: *ise_login
      state: present
      name: "{{ ise_global.ad_join_point_name }}"
      domain: "{{ ise_global.ad_domain_name }}"

**Example error**

TASK [Create AD Join Point] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: }
fatal: [ise33-2.ise.trappedunderise.com]: FAILED! => {"changed": false, "msg": "An error occured when executing operation. The error was: [400] - Resource Initialization Failed due to JSON invalidity: please if properties names are correct: enableDomainWhiteList\n{\n  \"ERSResponse\" : {\n    \"operation\" : \"POST-create-activedirectory\",\n    \"messages\" : [ {\n      \"title\" : \"Resource Initialization Failed due to JSON invalidity: please if properties names are correct: enableDomainWhiteList\",\n      \"type\" : \"ERROR\",\n      \"code\" : \"Application resource validation exception\"\n    } ],\n    \"link\" : {\n      \"rel\" : \"related\",\n      \"href\" : \"https://ise33-2.ise.trappedunderise.com/ers/config/activedirectory\",\n      \"type\" : \"application/xml\"\n    }\n  }\n}"}

**Expected behavior**
The module should successfully create an AD Join point with the minimum required attributes of 'name' and 'domain'. All other attributes are optional.

**Example of API JSON body**
{
    "ERSActiveDirectory": {
        "name": "ISELAB-AD",
        "domain": "domain.com"
    }
}

**Screenshots**
<img width="757" alt="Screenshot 2024-07-04 at 3 28 46 PM" src="https://github.com/CiscoISE/ansible-ise/assets/103554967/7f44c646-a895-4227-b45d-c27e6621379f">

**Environment (please complete the following information):**
* ISE version and patch: 3.3 patch 2
* Ansible version: 2.15.5
* ISE collection version: 2.6.1
* CiscoISESDK version: 2.1.2
* OS version: MacOS 14.5

**Additional context**
The module documentation should also be updated to reflect the actual required attributes.

**Comment by bvargasre** [comment]
Hi @grg1bbs, I tried the module, but I did not get the mentioned error, can you activate the debug and send me the output to check the flow?

**Comment by fmunozmiranda** [comment]
closed due inactivity.
