### ISSUE TITLE
reservation and support_bundle_download modules: different options have same name up to casing

### ISSUE THREAD

**Issue by felixfontein** [CiscoISE/ansible-ise#133]
The two modules have distinct options which are equal up to casing:
```
ERROR: plugins/modules/reservation.py:0:0: option-equal-up-to-casing: Multiple options/aliases are equal up to casing: option 'clientID', option 'clientId'
ERROR: plugins/modules/support_bundle_download.py:0:0: option-equal-up-to-casing: Multiple options/aliases are equal up to casing: option 'fileName', option 'filename'
```

These options look very much like they should be *aliases* of each other, instead of distinct options.

I.e. `clientID` should be an alias of `clientId` (or vice versa), instead of having two separate options `clientID` and `clientId`. Or are these actually two options that can be set to different values independently from each other?

Ref: https://github.com/ansible/ansible/pull/83530

**Comment by bvargasre** [comment]
Solved it in the new version 2.9.3
