### ISSUE TITLE
cisco.ise.mnt_session_active_list_info ise_reponse is null

### ISSUE THREAD

**Issue by htlgit00** [CiscoISE/ansible-ise#134]
**Prerequisites**
* [v] Have you tested the operation in the API directly?
* [v] Do you have the latest ISE Collection version?
* [v] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
Similar to #93 , cisco.ise.mnt_session_active_list_info returns valid xml response (count) but the response is not applied to the ise_response

**Expected behavior**
ise_response should include the value from <activeList noOfActiveSession="0"/>, not null

**Ansible-Playbook Output**
[PLAY [ise_servers] .txt](https://github.com/user-attachments/files/16169611/PLAY.ise_servers.txt)

**Environment (please complete the following information):**
* ISE version and patch: ISE 3.2 Patch 3
* Ansible version: 6.7
* ISE collection version: 2.9.2
* OS version: Ubuntu 22.04 LTS

**Additional context**
None.

**Comment by bvargasre** [comment]
Hi @htlgit00 the new version of ansible-ise 2.9.3 is now available
In the new version the problem was fixed, try with this version and let us know
I'm going to close this issue, in case the problem persists feel free to reopen it or create a new one
Regards
