### ISSUE TITLE
Trusted Certificate Update does not update friendly name

### ISSUE THREAD

**Issue by mac-myers** [CiscoISE/ansible-ise#136]
**Prerequisites**
* [ X] Have you tested the operation in the API directly?
* [X ] Do you have the latest ISE Collection version?
* [ X] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
ISE Trusted Certificates will not have their `friendlyName` updated when using the `cisco.ise.trusted_certificate` module, even if the friendlyName specified in the module is different than what currently exists on ISE.

**Expected behavior**
If a new friendly name is provided in the task, is it expected that the task will update the trusted certificate friendly name in ISE.

**Output**
Attempting to change the friendly name will result in `result: Object already present`. 

**Environment (please complete the following information):**
* ISE version and patch: 3.2.0.542 patch 4, 5
* Ansible version: ansible [core 2.15.5]       python version = 3.11.5
* ISE collection version: cisco.ise       2.5.16
* OS version: macOS Sonoma 14.5

**Additional context**

The module seems to look for `name` in the ISE response, but ISE returns it as `friendlyName` so it cannot find it to compare them. 
https://github.com/CiscoISE/ansible-ise/blob/2f159ef0bec511d0bf7c21135df9353f64930bd4/plugins/action/trusted_certificate.py#L188

**Comment by bvargasre** [comment]
Hi @mac-myers the new version of ansible-ise 2.9.3 is now available
In the new version the problem was fixed, try with this version and let us know
I'm going to close this issue, in case the problem persists feel free to reopen it or create a new one
Regards
