### ISSUE TITLE
cisco.ise.pan_ha object has no attribute 'enable_pan_ha'

### ISSUE THREAD

**Issue by bgoulet00** [CiscoISE/ansible-ise#141]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [X ] Do you have the latest ISE Collection version?
* [X ] Review the [compatibility matrix](https://github.com/CiscoISE/ansible-ise/tree/main#compatibility-matrix) before opening an issue.

**Name of the module**
cisco.ise.pan_ha

**Describe the bug**
on a brand new ISE deployment with no prior HA configuration cisco.ise.pan_ha does not work and returns an error.  cisco.ise.pan_ha_update, intended to update a pre-existing HA config, does work at configuring HA, even though there is no pre-existing config.

**Expected behavior**
"ise_response": {
        "success": {
            "message": "Pan HA has been enabled successfully"

**Screenshots**
- name: configure HA for PAN nodes 
      cisco.ise.pan_ha:
        ise_hostname: "{{ inventory_hostname }}"
        ise_username: "{{ ansible_user }}"
        ise_password: "{{ ise_gui_password }}"
        ise_verify: false
        state: present
        failedAttempts: 5
        isEnabled: true
        pollingInterval: 120
        primaryHealthCheckNode: "{{ ise_zone2_healthcheck_node }}"
        secondaryHealthCheckNode: "{{ ise_zone1_healthcheck_node }}"

The full traceback is:
Traceback (most recent call last):
  File "/home/bgoulet/.ansible/collections/ansible_collections/cisco/ise/plugins/plugin_utils/ise.py", line 222, in exec
    func = getattr(family, function)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PanHa' object has no attribute 'enable_pan_ha'
fatal: [pri]: FAILED! => {
    "changed": false,
    "msg": "An error occured when retrieving operation. The error was: 'PanHa' object has no attribute 'enable_pan_ha'"
}

**Environment (please complete the following information):**
* ISE version and patch: 3.3 patch 2
* Ansible version:  2.15.12
* ISE collection version:  ciscoisesdk 2.2.3, cisco.ise 2.9.3
* OS version:  Ubuntu 24.04 LTS, Python 3.12.3

**Comment by fmunozmiranda** [comment]
Please try it with new version and update us.

**Comment by fmunozmiranda** [comment]
closed due inactivity
