### ISSUE TITLE
Collection not compatible with ansible.utils 5.x.y

### ISSUE THREAD

**Issue by felixfontein** [CiscoISE/ansible-ise#144]
This collection is currently not compatible with ansible.utils 5.x.y per its galaxy.yml `dependencies` entry. ansible.utils 5.0.0 has been released ~four months ago.

According to the Ansible inclusion requirements (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#collection-dependencies), if you depend on any other collection, you have to make sure to be compatible to ansible.util's latest version in a timely manner.

The requirements state:

> In case a collection depends on releases of a new major version outside of this version range that will be included in the next major Ansible release, the dependent collection will be removed from the next major Ansible release. The cut-off date for this is feature freeze.

The Ansible 11 feature freeze is on November 5th, which is in three weeks. Please make sure to:
1. Update galaxy.yml's `dependencies` entry and make sure your collection is compatible to ansible.utils 5.x.y;
2. Release a new version with that change (note that dependency range updates should only be done in minor or major releases).

Thanks!

**Comment by fmunozmiranda** [comment]
Updated, If there is nothing else I can help you with, please close the issue.

**Comment by felixfontein** [comment]
Thanks, bumping the requirements and doing the release fixed this. (Verified in https://github.com/ansible-community/ansible-build-data/pull/482.)

**Comment by mariolenz** [comment]
Thanks @fmunozmiranda!
