### ISSUE TITLE
Radius vs TACACS Network Access Device inconsistency 

### ISSUE THREAD

**Issue by ekorneyc** [CiscoISE/ansible-ise#15]
Hello,

I would like to report an issue with the Ansible collection. When we create a TACACS device as part of the playbook, each subsequent run of the same playbook will result in "ok", meaning nothing to be changed, however if devices is configured with Radius, it will all the time show the "changed" status.

According to my reverse engineering the issue is happening because you replace the password for RADIUS with ***, so it treats it always "new", while for TACACS you send it in clear.

--- Task results:
TASK [Create or update WLC6] *****************************************************************************************************************************************************
changed: [ise_server]

TASK [Create or update BSNS-4451-4] **********************************************************************************************************************************************
ok: [ise_server]

--- With debugs:

WLC6:
  "authenticationSettings": {
            "dtlsRequired": false,
            "enableKeyWrap": false,
            "enableMultiSecret": "false",
            "keyInputFormat": "ASCII",
            "networkProtocol": "RADIUS",
            "radiusSharedSecret": "******"

BSNS-4451-4:
        "name": "BSNS-4451-4",
        "profileName": "Cisco",
        "tacacsSettings": {
            "connectModeOptions": "ON_LEGACY",
            "sharedSecret": "cisco"

**Comment by einarnn** [comment]
This issue will be addressed in ISE 3.1 Patch 1. The `radiusSharedSecret` will again be available in clear text.

**Comment by ekorneyc** [comment]
Thank you. No more questions from my side on this issue.

**Comment by wastorga** [comment]
@einarnn, @ekorneyc
I will close the issue since Cisco ISE 3.1.1 was released.
Moreover, it appears it has more to do with the API than the Ansible collection.
