### ISSUE TITLE
Issue with Join to Active Directory operation

### ISSUE THREAD

**Issue by ekorneyc** [CiscoISE/ansible-ise#16]
Hello,

If ISE is already joined to the Active Directory, subsequent run of the playbook will fail. See below. Issue is reproducible in the lab, feel free to reach out if you require access.

TASK [Join all Nodes to Active Directory] ****************************************************************************************************************************************
task path: /Users/ekorneyc/Documents/Work/Ansible/example/ise-playbook.yaml:55
fatal: [ise_server]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. The error was: [500] - Operation [join] failed [com.cisco.cpm.ers.api.exception.ERSCRUDHandlerException: nodes not able to join/remove : [ISE31-1ek.example.com]\n{\n  \"ERSResponse\" : {\n    \"operation\" : \"PUT-joinAllNodes-activedirectory\",\n    \"messages\" : [ {\n      \"title\" : \"Operation [join] failed [com.cisco.cpm.ers.api.exception.ERSCRUDHandlerException: nodes not able to join/remove : [ISE31-1ek.example.com]\",\n      \"type\" : \"ERROR\",\n      \"code\" : \"CRUD operation exception\"\n    } ],\n    \"link\" : {\n      \"rel\" : \"related\",\n      \"href\" : \"https://10.48.17.20/ers/config/activedirectory/865afa30-3d50-11ec-9423-fac22d4e456e/joinAllNodes\",\n      \"type\" : \"application/xml\"\n    }\n  }\n}"
}
...ignoring

**Comment by wastorga** [comment]
Hi, @ekorneyc . This issue seems to be related to the API, as suggested by the 'msg'.
But at the moment, I am unsure of the best way to solve or work around the issue for subsequent runs. So, I will take a closer look tomorrow.

**Comment by wastorga** [comment]
@ekorneyc

I think you could wrapped it in a block ... rescue structure.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#handling-errors-with-blocks

**Comment by wastorga** [comment]
Hi, @ekorneyc.
Did you look into the link shared previously? Can we close this issue?

**Comment by wastorga** [comment]
Hi, @ekorneyc.
Gently reminder to comment. If there is no comment, I will close this issue due to inactivity the following weekend.

**Comment by wastorga** [comment]
Hi, @ekorneyc.
Another, gently reminder to comment.
