### ISSUE TITLE
Cisco ISE Network Device Group Fetch

### ISSUE THREAD

**Issue by yzmar4real** [CiscoISE/ansible-ise#24]
Hi, 
When you try to pull the existing device groups from ISE, the error 400 - page 2 does not exist keeps on coming up. When i look at the URL being pushed, its  href: https://<ise-ip>/ers/config/networkdevicegroup?page=2 . Even when there's no page referenced this is the standard URL pushed. When i use ERS on postman alone with https://<ise-ip>/ers/config/networkdevicegroup - everything works as should.

**Comment by wastorga** [comment]
Hi, @yzmar4real
This issue seems to be caused by a problem in the ciscoisesdk. The problem is that only 404 errors are captured when attempting to get to the next page. I will make the necessary updates and notify you when done.
