### ISSUE TITLE
Error in network_device_info.py

### ISSUE THREAD

**Issue by jrogersfaneuil** [CiscoISE/ansible-ise#28]
**Prerequisites**
* [x] Have you tested the operation in the API directly? Mostly (Curl came back empty)
* [x] Do you have the latest ISE Collection version? Yes

**Describe the bug**
I'm running The following playbook in the Cisco ISE 3.1 sandbox:
`- hosts: ise_servers
  gather_facts: no
  tasks:
    - name: Get all network devices
      cisco.ise.network_device_info:
        ise_hostname: <lab ise IP>
        ise_username: admin
        ise_password:<admin pw>
        ise_verify: False`

Following error output was provided:

ERROR! Unexpected Exception, this is probably a bug: invalid syntax (network_device_info.py, line 89)
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 127, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 241, in run
    play_return = strategy.run(iterator, play_context)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 248, in run
    action = action_loader.get(task.action, class_only=True)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 557, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 535, in _load_module_source
    module = imp.load_source(to_native(full_name), to_native(path), module_file)
  File "/home/developer/.ansible/collections/ansible_collections/cisco/ise/plugins/action/network_device_info.py", line 89
    response = ise.exec(

SyntaxError: invalid syntax

**Expected behavior**

A single network device should have been returned

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc. I have a screenshot, but no way to upload it

**Environment (please complete the following information):**
* ISE version and patch:  3.1
* Ansible version:  
* ansible 2.9.4
  config file = None
  configured module search path = [u'/home/developer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

* ISE collection version:
* OS version: 

**Additional context**

**Comment by jrogersfaneuil** [comment]
![image](https://user-images.githubusercontent.com/66491475/160215847-1cf14402-af62-4d51-a1f2-c3bf266019d0.png)

**Comment by jrogersfaneuil** [comment]
''- hosts: ise_servers 
gather_facts: no 
tasks: 
- name: Get all network devices 
    cisco.ise.network_device_info: ise_hostname: <lab ise IP> 
    ise_username: admin 
    ise_password:<admin pw> 
    ise_verify: False''

**Comment by wastorga** [comment]
Python >= 3.6, as the Cisco ISE SDK doesn't support Python version 2.x

**Comment by jrogersfaneuil** [comment]
Good catch. That was a bad assumption on my part. I'll see if I can update Python on the lab machine and try again. Thanks!

**Comment by jrogersfaneuil** [comment]
The sandbox is still having python version issues. I'll find a 3.6 machine later and open another issue if the error persists.
