### ISSUE TITLE
mnt_session_by_mac_info returning 500 error

### ISSUE THREAD

**Issue by collinsjas** [CiscoISE/ansible-ise#34]
**Prerequisites**
* [x ] Have you tested the operation in the API directly?
* [x ] Do you have the latest ISE Collection version?

**Describe the bug**
When using cisco.ise.mnt_session_by_mac_info I am getting error 500 from the server.

I am not getting any errors with cisco.ise.mnt_session_by_ip_info with the same device.

**Expected behavior**
I expect to get XML response in from ISE with sessionParameters

**Screenshots**
![image](https://user-images.githubusercontent.com/36859119/166833699-cd0223ad-8bef-418c-9850-69ee41570053.png)

**Environment (please complete the following information):**
* ISE version and patch: 3.1.0.518
* Ansible version: 2.12
* ISE collection version: 2.0.0 and 2.3.2
* OS version: RHEL8

**Additional context**

**Comment by collinsjas** [comment]
Found the issue I was having.  The letters needed to be UPPERCASE.  I applied a "| upper" to the variable being passed in and that corrected the error.

**Comment by fmunozmiranda** [comment]
Hey @collinsjas, is there anything else I can help you?

**Comment by collinsjas** [comment]
No, sorry meant to close with comment.
