### ISSUE TITLE
Multi-page data parsing error when retrieving defined SGTs.

### ISSUE THREAD

**Issue by bootsmo** [CiscoISE/ansible-ise#45]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [x] Do you have the latest ISE Collection version?

**Describe the bug**
Data type error when parsing  multi-page SGT list from SDK.  Ansible task used was: 
```
    - name: Get list of all current SGTs.
      cisco.ise.sgt_info:
        <<: *ise_login
        sortasc: value
      register: sgt_table
```

``` 
fatal: [<redacted>]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. Check the configuration of your API Settings and API Gateway settings on your ISE server. This collection assumes that the API Gateway, the ERS APIs and OpenAPIs are enabled. You may want to enable the (ise_debug: True) argument. The error was: We were expecting to receive an instance of one of the following types: 'basestring'or 'None'; but instead we received ['value'] which is a 'list'."
```

**Expected behavior**
Retrieve multi-page list of defined SGTs from ISE.

**Screenshots**
Text file attached showing returned data, error message, ansible collections and versions.

**Environment (please complete the following information):**
* ISE version and patch: 3.1 Patch 1
* Ansible version: 2.10.8
* ISE collection version: 2.5.0
* OS version: Ubuntu Jammy container

**Additional context**
[IssueData-ErrorGettingSgtList.txt](https://github.com/CiscoISE/ansible-ise/files/9064673/IssueData-ErrorGettingSgtList.txt)

**Comment by bvargasre** [comment]
Hi @bootsmo, ciscoisesdk has been updated to version 2.0.4, so try this new version and tell me if it works.

**Comment by bootsmo** [comment]
@bvargasre - Upgrading ciscoisesdk to v2.0.4 appears to have corrected the issue.  My testing is showing the full data set being returned as expected.
