### ISSUE TITLE
Inaccurate documentation

### ISSUE THREAD

**Issue by RyanMBess** [CiscoISE/ansible-ise#54]
Seems a number of links in the documentation doesn't have all parameters marked as required.  Here's an example
https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_module.html#ansible-collections-cisco-ise-endpoint-module

Per the above link only ise_hostname, ise_password, ise_username are the only parameters needed to create and endpoint.  Please update so we know what parameters are required to use this module (please do the same for all modules)

**Comment by bvargasre** [comment]
Hi @RyanMBess This problem will be mentioned to cisco since they are the ones who provide us with the api documentation to generate the libraries, and it is expected to be solved in future versions.

**Comment by RyanMBess** [comment]
Thank you.

**Comment by RyanMBess** [comment]
Hi @bvargasre,
How goes updating the documentation.  In this example https://docs.ansible.com/ansible/latest/collections/cisco/ise/sgt_module.html#ansible-collections-cisco-ise-sgt-module you MUST have the value attribute populated or you will be unable to create the SGT.  Per the link it's not a required field.

**Comment by bvargasre** [comment]
Cisco has been informed about the `required` problem, but we have not been provided with new documentation yet.
#
For the moment I updated the documentation of the required fields for the creation of an sgt from the `sgt` module.
The change can be seen here
https://ciscoise.github.io/ansible-ise/main/plugins/sgt_module.html#ansible-collections-cisco-ise-sgt-module
The changes will be reflected in `docs.ansible.com` when Ansible releases a new version.

**Comment by fmunozmiranda** [comment]
Closed due inactivity
