### ISSUE TITLE
SXP Connection create incorrectly requires ID parameter

### ISSUE THREAD

**Issue by bootsmo** [CiscoISE/ansible-ise#61]
**Prerequisites**
* [X] Have you tested the operation in the API directly?
* [X] Do you have the latest ISE Collection version?

**Describe the bug**
Creation of an SXP connection requires parameter "id".  The error message also erroneously claims that the parameter "state" is present when it is not part of the request body.  The SXP connection is subsequently not created in the ISE deployment.

**Expected behavior**
Create new SXP connection without requirement of a non-existent ID parameter.

**Screenshots**
Text file with Ansible and Postman output attached here.
[SxpConnIssueData.txt](https://github.com/CiscoISE/ansible-ise/files/9758905/SxpConnIssueData.txt)

**Environment (please complete the following information):**
* ISE version and patch:  3.1 patch 1
* Ansible version: 2.10.8
* ISE collection version: 2.5.5
* OS version: Ubuntu Jammy container.

**Additional context**

**Comment by bvargasre** [comment]
Hi @bootsmo
Ansible-ise v2.5.6. is available. Feel free to test it and close or comment if necessary.

**Comment by bootsmo** [comment]
Confirmed - functionality now appears to be working as desired.
Thanks again.
