### ISSUE TITLE
Populate Cisco ISE Endpoint Group by name

### ISSUE THREAD

**Issue by RyanMBess** [CiscoISE/ansible-ise#71]
When creating an endpoint in ISE, please support allowing that endpoint to be added to an endpoint group via it's name.  Currently as best i can tell you have to get the endpoint group ID then you can add the endpoint to the endpoint group via it's ID.  If I'm missing something please provide the code that allows you to add an endpoint to an endpoint group via the endpoint group name.  

I've seen the example here (https://github.com/CiscoISE/ansible-ise/blob/main/playbooks/endpoint.yml)  for how to do this singularly where you are tattooing the endpoint group name in to pull the id, then add the new endpoint to that group.  This does not scale.  I am trying to iterate over a large CMDB where the CMDB has the endpoint group name as part of the asset info so a human can understand what that endpoint group is when looking at the CMDB.

**Comment by 1homas** [comment]
Ryan, I agree with you that both the `endpointgroup`'s `id` and `name` should be supported for flexibility when specifying the `endpoint`'s `endpointgroup`.
I have submitted this to our PM to create a user story and prioritization.
There are several other ISE API resources that have a similar requirement on the ID and I have added those.
