### ISSUE TITLE
Not possible to create an authorization rule with an OR or AND block condition

### ISSUE THREAD

**Issue by paulcana** [CiscoISE/ansible-ise#72]
**Prerequisites**
* [ x] Have you tested the operation in the API directly?
* [ x] Do you have the latest ISE Collection version?

**Describe the bug**
When using authorization rule module cisco.ise.network_access_authorization_rules, the ansible playbook is failing.
Error message is error 400: request has bad input format in the body
It is failing when trying to use multiple conditions for the rule
```rule:
      condition:
        conditionType: ConditionAndBlock
        isNegate: false
        children:
        - conditionType: ConditionReference
          name: Cond_Authz_AD_DomainComputers
          isNegate: false
          id: "{{domain_computer.ise_response.id}}"
        - conditionType: ConditionReference
          isNegate: false
          id: "{{non_compliant.ise_response.id}}"
```
**Expected behavior**
Expected behavior is message 201 with the rule properly created.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.
![image](https://user-images.githubusercontent.com/69456907/201939136-f5990a22-62b8-4a4d-97c3-896c74065a4c.png)

**Environment (please complete the following information):**
* ISE version and patch: 3.1patch3
* Ansible version: 2.10.15
* ISE collection version: 2.5.9
* OS version: Alpine Linux 3.14

**Additional context**
By testing with postman we noticed that API requires to provide "link", "name" and "description" parameters in the body of the request, even if in the case of ConditionReference type, only "id" is mandatory.
As you can see on the screenshot, in the API call, we set link parameter and description to null and the call was successful.
Using ansible module we have no way to set the parameters to null and thus it's not possible to setup new authorization rule with multiple conditions.
In addition the module is not idempotent

**Comment by bootsmo** [comment]
I think the issue may be with ISE 3.1 patch 3.  We know some APIs changed with patch 4, and I've got unconfirmed reports of API changes in patch 3 as well.
I ran a playbook with multiple and/or conditions last night using collection version 2.5.9 against ISE 3.1 with patch 1 and had no issues.  The main difference between your condition block and mine is that I didn't include the 'name' attribute in the child condition.

**Comment by paulcana** [comment]
Hello @bootsmo 
Indeed there is one bug fix on patch 4 which looks related to our issue
https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwb82814

I will upgrade to 3.1 patch 4 and test again, then I'll let you know about the result

**Comment by bvargasre** [comment]
Hi @paulcana , in version 2.5.10 network_access_authorization_rules should be idempotent.
The other thing seems to be an API problem and not ansible as such, as mentioned in 3.1 patch 1 works fine.
