### ISSUE TITLE
ISE 3.1Patch 4 Network device Group has different attributes

### ISSUE THREAD

**Issue by Rajasekar0104** [CiscoISE/ansible-ise#73]
**Prerequisites**
* [x] Have you tested the operation in the API directly? Yes
* [x] Do you have the latest ISE Collection version?

**Describe the bug**
When we are trying to create a Network Device Group via Ansible in ISE 3.1 Patch 4 we are getting Error

*Failed: Invalid JSON: Unrecognized field \"othername\" *

Ansible has the Defined structure of for network device groups as 
I) Name : string
II) other name : string

where as the ISE 3.1 patch 4 has 

I) Name:
II) ndg:

 
**Expected behavior**
Excepted is to get HTTP Status:	200 (OK)

**Screenshots**
Ansible 

![image](https://user-images.githubusercontent.com/118898832/203538707-f42cd45e-b2e5-4dd7-8339-129c59fa156e.png)
ISE 3.1 patch 4 
![image](https://user-images.githubusercontent.com/118898832/203570565-87da0cd8-901d-4fdb-8121-b68833e89e98.png)

**Environment (please complete the following information):**
* ISE version and patch: 3.1 / 4
* Ansible version:  3.0
* ISE collection version: 2.5.9
* OS version:  Alpine Linux 3.13

**Additional context**
As both the variables are different between ansible and cisco for Creation of Network Device group we face an Issue.

**Comment by einarnn** [comment]
I can only apologize for this. This is a backwards incompatible change that will be rolled back.

**Comment by Rajasekar0104** [comment]
Thanks @einarnn  For the responce. I see the same issue in ISE 3.2 as well. So probably will it stick with _ndg_

**Comment by einarnn** [comment]
@Rajasekar0104

Please note that this will be rolled back on 3.2 as well.

**Comment by bvargasre** [comment]
Hi @Rajasekar0104, as einarnn mentioned, this was a CiscoISE issue
you can see it here: https://bst.cisco.com/bugsearch/bug/CSCwd24304
I'm going to close this issue, in case the problem persists feel free to reopen it or create a new one
Regards
