### ISSUE TITLE
Unable to update Authorization Policies

### ISSUE THREAD

**Issue by ryanbess-niaid** [CiscoISE/ansible-ise#81]
If you create an authorization policy via code OR via the API and you then need to update that authorization policy you can not via the API nor the modules.  In this example if you forget to add a securityGroup to the authz policy then attempt to update that now existing authz policy, it errors out both via the api and with the modules.  You can use the below as an example json.  Just remove the securityGroup section and run it through the api, then add the securityGroup section and re-run it.  It should error with a 400 object already found.  Running ISE 3.1 patch 3.  

```json
{
	"state": "present",
	"rule": {
		"default": false,
		"name": "IAC_Authorization Policy",
		"rank": 0,
		"state": "enabled",
		"condition": {
			"link": null,
			"conditionType": "ConditionAttributes",
			"isNegate": false,
			"dictionaryName": "IdentityGroup",
			"attributeName": "Name",
			"operator": "equals",
			"dictionaryValue": null,
			"attributeValue": "Endpoint Identity Groups:IAC_Lab1"
		}
	},
	"profile": [
		"IAC_SNI_Authorization_Profile"
	],
	"securityGroup": "IAC_Lab1_SGT",
	"policyId": "somepolicysetid"
}
```

**Comment by einarnn** [comment]
@ryanbess-niaid As I think has been discussed on a thread you have with others, the ISE Ansible modules are not necessarily idempotent. This is a known issue, but one which may not be documented adequately. To perform an incremental update as you describe above you will need to add, at the same level as `policyId`, the key `id`, with the value set to the UUID returned when you created the policy rule.

Apologies for the lack of documentation of this. Please note that this applies to most other create/update/delete changes you may want to run through Ansible.

**Comment by ryanbess-niaid** [comment]
Confirmed, if you add the id it works.  I will add the id moving forward.  Yes please update the documentation and examples as here https://github.com/CiscoISE/ansible-ise/blob/main/playbooks/network_access_authorization_rules.yml in the "- name: Create or update an network_access_authorization_rules" section, it states you do not need the id of the rule.

**Comment by einarnn** [comment]
@ryanbess-niaid, please see:

https://github.com/CiscoISE/ansible-ise/commit/30ca3a4cb6303094e923c81cb1f7918b1c4ec7ef

Closing this issue for now!
