### ISSUE TITLE
Unable to Filter

### ISSUE THREAD

**Issue by ai-ryanbess** [CiscoISE/ansible-ise#87]
When using the Filter parameter it does not work. https://docs.ansible.com/ansible/latest/collections/cisco/ise/endpoint_info_module.html#parameter-filter.  in the below i'm asking for ISE to return all mac addresses that have the number 6.  No results are found.  

- name: Get Endpoint Info
  cisco.ise.endpoint_info:
   ise_hostname: "{{  ansible_host  }}"
   ise_username: "{{  ansible_user  }}"
   ise_password: "{{  ansible_password  }}"
   ise_verify: "{{  ise_verify  }}"
   #name: "{{  item.mac_address  }}"
   filter: [mac.CONTAINS.'6']
  register: result
    
- name: Print Result
  debug:
    msg:  "{{  result  }}"

**Comment by bootsmo** [comment]
@ai-ryanbess Try using ``` filter: ['mac.CONTAINS.6'] ```

**Comment by ai-ryanbess** [comment]
Thanks that worked.  Can you please update the documentation to reflect an example.  Also please update the below to have a comma between field and operator.  As it currently can be read it looks like it's not a triplet that's needed but rather only 2, a "filed operator" and "value" 


Filter query parameter. **Simple filtering** should be available through the filter query string parameter. The structure of a filter is a triplet of **field operator** and value separated with dots. More than one filter can be sent. The logical operator common to ALL filter criteria will be by default AND, and can be changed by using the “filterType=or” query string parameter.
