### ISSUE TITLE
Check if PAN is Functioning

### ISSUE THREAD

**Issue by ai-ryanbess** [CiscoISE/ansible-ise#89]
Please create a module that supports a simple test to validate the PAN is up and running.  The use case would be to run this playbook first, get some sort of known response that defines the PAN is active and accepting updates, and then run additional playbooks.

**Comment by jbogarin** [comment]
Do you think any of these modules might work?
https://docs.ansible.com/ansible/latest/collections/cisco/ise/pan_ha_info_module.html#ansible-collections-cisco-ise-pan-ha-info-module

https://docs.ansible.com/ansible/latest/collections/cisco/ise/personas_check_standalone_module.html#ansible-collections-cisco-ise-personas-check-standalone-module

**Comment by ai-ryanbess** [comment]
@jbogarin saw those and only ran the pan-ha-info one.  Unfortunately my current PAN is not in HA.  Ultimately i'd liek for Cisco to tell me how via automation to know if the primary pan is up and functioning.  

I'll try the the other one in the morning.

**Comment by fmunozmiranda** [comment]
Hi @ai-ryanbess do you test it?
Please update us or issue will be closed in next 24 hours.
